### ISSUE TITLE
somethings wrong with the wind/weather display

### ISSUE THREAD

**Issue by spiantino** [spiantino/baseball-stats#25]
7:05PM Yankee Stadium · 87.02 ◦ Partly Cloudy · Wind 8.45mph 13mph L To R

probably should be more like

7:05PM Yankee Stadium · 87◦ Partly Cloudy · Wind 13mph L To R

**Comment by aleko-** [comment]
8.45mph is from the darksky api, 13mph was from the game data so it shouldn't be showing up here (fixed it in the code). Should the speed be rounded to a whole number or keep it with two decimal points?

**Comment by spiantino** [comment]
rounding is probably better, not like that level of precision is going to be interpretable
